SELECT tblManifoldQualificationsDocuments.Document_ID, tblManifoldQualificationsDocuments.[Document Name], tblManifoldQualificationsDocuments.ID, tblManifoldQualificationsDocuments.[Date Added]
FROM tblManifoldQualificationsDocuments;

